/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.apartment_system;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author zhixu
 */
public class ResidentMainPage extends javax.swing.JFrame {
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    
    /**
     * Creates new form ResidentMainPage
     */
    public ResidentMainPage() {
        
        initComponents();
                
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginFrame = new javax.swing.JFrame();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        MenuBarPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        profilePanelbtn = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        residentProfilePanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        residentUnitLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        editProfileBtn = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        residentVehicleTabel = new javax.swing.JTable();
        residentNameLabel = new javax.swing.JLabel();
        residentPhoneLabel = new javax.swing.JLabel();
        residentEmailLabel = new javax.swing.JLabel();
        residentICLabel = new javax.swing.JLabel();
        residentIDLabel = new javax.swing.JLabel();
        editResidentProfilePanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        residentNameTextField = new javax.swing.JTextField();
        residentPhoneTextField = new javax.swing.JTextField();
        residentICTextField = new javax.swing.JTextField();
        residentEmailTextField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        editVehicleTable = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        deleteVehiclebtn = new javax.swing.JButton();
        saveEditBtn = new javax.swing.JButton();
        billPanel = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        pendingTable = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        historyTable = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        paybyCreditBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        cardNumberTextField = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        cardHolderTextField = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        monthSelection = new javax.swing.JComboBox<>();
        yearSelection = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        cvvTextField = new javax.swing.JTextField();
        paybtn = new javax.swing.JButton();
        billIDLabel = new javax.swing.JLabel();

        LoginFrame.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane2.setPreferredSize(new java.awt.Dimension(1350, 1040));

        jPanel5.setPreferredSize(new java.awt.Dimension(1350, 1040));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1150, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 569, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("tab1", jPanel5);

        LoginFrame.getContentPane().add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, -28, 1150, 600));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1400, 1040));

        MenuBarPanel.setBackground(new java.awt.Color(82, 178, 178));
        MenuBarPanel.setPreferredSize(new java.awt.Dimension(267, 1040));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setText("Sparrow Apartment");

        jButton1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton1.setText("Bills");
        jButton1.setPreferredSize(new java.awt.Dimension(268, 61));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton2.setText("Forum");
        jButton2.setPreferredSize(new java.awt.Dimension(268, 61));

        profilePanelbtn.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        profilePanelbtn.setText("Profile");
        profilePanelbtn.setPreferredSize(new java.awt.Dimension(268, 61));
        profilePanelbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profilePanelbtnActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton4.setText("Notifications");
        jButton4.setPreferredSize(new java.awt.Dimension(268, 61));

        javax.swing.GroupLayout MenuBarPanelLayout = new javax.swing.GroupLayout(MenuBarPanel);
        MenuBarPanel.setLayout(MenuBarPanelLayout);
        MenuBarPanelLayout.setHorizontalGroup(
            MenuBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuBarPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addContainerGap(34, Short.MAX_VALUE))
            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(profilePanelbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        MenuBarPanelLayout.setVerticalGroup(
            MenuBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuBarPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addComponent(profilePanelbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(665, Short.MAX_VALUE))
        );

        jPanel2.setMinimumSize(new java.awt.Dimension(1350, 1040));
        jPanel2.setPreferredSize(new java.awt.Dimension(1200, 1040));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(82, 178, 178));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1160, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 80));

        jTabbedPane1.setPreferredSize(new java.awt.Dimension(100, 1040));

        residentProfilePanel.setBackground(new java.awt.Color(232, 239, 239));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setText("Resident Profile");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        residentUnitLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N

        editProfileBtn.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        editProfileBtn.setText("Edit Profile");
        editProfileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editProfileBtnActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jButton6.setText("Chnage Password");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(residentUnitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(editProfileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)))
                .addGap(75, 75, 75))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(249, 249, 249))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(residentUnitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(editProfileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel4.setText("Basic Information");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setText("Resident Name:");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setText("IC No:");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setText("Phone Number:");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setText("Email:");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel9.setText("Contact Information");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel10.setText("Vehicle Information");

        residentVehicleTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Brand", "Model", "Plate Number", "Color"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(residentVehicleTabel);

        residentNameLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        residentPhoneLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        residentEmailLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        residentICLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        residentIDLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 1)); // NOI18N

        javax.swing.GroupLayout residentProfilePanelLayout = new javax.swing.GroupLayout(residentProfilePanel);
        residentProfilePanel.setLayout(residentProfilePanelLayout);
        residentProfilePanelLayout.setHorizontalGroup(
            residentProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(residentProfilePanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(residentProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(residentProfilePanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(residentIDLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(residentProfilePanelLayout.createSequentialGroup()
                        .addGroup(residentProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(residentProfilePanelLayout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(residentProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(residentProfilePanelLayout.createSequentialGroup()
                                        .addGap(72, 72, 72)
                                        .addGroup(residentProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel10)
                                            .addGroup(residentProfilePanelLayout.createSequentialGroup()
                                                .addGroup(residentProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel5)
                                                    .addComponent(jLabel6))
                                                .addGap(33, 33, 33)
                                                .addGroup(residentProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(residentNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(residentICLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(residentProfilePanelLayout.createSequentialGroup()
                                                .addGroup(residentProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel7)
                                                    .addComponent(jLabel8))
                                                .addGap(18, 18, 18)
                                                .addGroup(residentProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(residentEmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(residentPhoneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(residentProfilePanelLayout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(112, Short.MAX_VALUE))))
        );
        residentProfilePanelLayout.setVerticalGroup(
            residentProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(residentProfilePanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(residentIDLabel)
                .addGap(5, 5, 5)
                .addGroup(residentProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(residentProfilePanelLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addGroup(residentProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(residentNameLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(residentProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(residentICLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addGroup(residentProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(residentPhoneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(residentProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(residentProfilePanelLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(41, 41, 41)
                                .addComponent(jLabel10))
                            .addComponent(residentEmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(469, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab1", residentProfilePanel);

        editResidentProfilePanel.setBackground(new java.awt.Color(232, 239, 239));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel11.setText("Resident Name");

        jLabel12.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel12.setText("Resident IC");

        jLabel13.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel13.setText("Resident Phone Number");

        jLabel14.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel14.setText("Contact Information");

        jLabel15.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel15.setText("Resident Email");

        jLabel16.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel16.setText("Vehicle Information");

        residentNameTextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        residentPhoneTextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        residentICTextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        residentEmailTextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        editVehicleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Brand", "Model", "Plate Number", "Color"
            }
        ));
        jScrollPane2.setViewportView(editVehicleTable);

        jLabel17.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel17.setText("Basic Information");

        jButton7.setText("Add");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        deleteVehiclebtn.setText("Delete");
        deleteVehiclebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteVehiclebtnActionPerformed(evt);
            }
        });

        saveEditBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        saveEditBtn.setText("Save Change");
        saveEditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveEditBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout editResidentProfilePanelLayout = new javax.swing.GroupLayout(editResidentProfilePanel);
        editResidentProfilePanel.setLayout(editResidentProfilePanelLayout);
        editResidentProfilePanelLayout.setHorizontalGroup(
            editResidentProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editResidentProfilePanelLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(editResidentProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editResidentProfilePanelLayout.createSequentialGroup()
                        .addComponent(saveEditBtn)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(editResidentProfilePanelLayout.createSequentialGroup()
                        .addGroup(editResidentProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editResidentProfilePanelLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(deleteVehiclebtn))
                            .addGroup(editResidentProfilePanelLayout.createSequentialGroup()
                                .addGroup(editResidentProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(residentICTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12)
                                    .addComponent(residentNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(93, 93, 93))
                    .addGroup(editResidentProfilePanelLayout.createSequentialGroup()
                        .addGroup(editResidentProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(residentEmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addGroup(editResidentProfilePanelLayout.createSequentialGroup()
                                .addGroup(editResidentProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(residentPhoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel17))
                                .addGap(136, 136, 136)
                                .addComponent(jLabel16)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        editResidentProfilePanelLayout.setVerticalGroup(
            editResidentProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editResidentProfilePanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(editResidentProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editResidentProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addGroup(editResidentProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(deleteVehiclebtn, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editResidentProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(editResidentProfilePanelLayout.createSequentialGroup()
                        .addComponent(residentNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(residentICTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(residentPhoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(residentEmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(saveEditBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(524, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab2", editResidentProfilePanel);

        billPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel18.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel18.setText("Bill");

        jLabel19.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel19.setText("Pending Payment");

        pendingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Bill Type", "Amount"
            }
        ));
        jScrollPane3.setViewportView(pendingTable);

        jLabel20.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel20.setText("Payment History");

        historyTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Bill Type", "Payment Date"
            }
        ));
        jScrollPane4.setViewportView(historyTable);

        jButton3.setBackground(new java.awt.Color(0, 0, 204));
        jButton3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Pay by Paypal");

        paybyCreditBtn.setBackground(new java.awt.Color(204, 0, 51));
        paybyCreditBtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        paybyCreditBtn.setForeground(new java.awt.Color(255, 255, 255));
        paybyCreditBtn.setText("Pay by Credit Card");
        paybyCreditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paybyCreditBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout billPanelLayout = new javax.swing.GroupLayout(billPanel);
        billPanel.setLayout(billPanelLayout);
        billPanelLayout.setHorizontalGroup(
            billPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(billPanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(billPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(billPanelLayout.createSequentialGroup()
                        .addGroup(billPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(billPanelLayout.createSequentialGroup()
                        .addGroup(billPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(billPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(paybyCreditBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(343, 343, 343))))
        );
        billPanelLayout.setVerticalGroup(
            billPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(billPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addGap(45, 45, 45)
                .addComponent(jLabel19)
                .addGap(42, 42, 42)
                .addGroup(billPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(billPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(jLabel20))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, billPanelLayout.createSequentialGroup()
                        .addComponent(paybyCreditBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(355, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab3", billPanel);

        jPanel3.setBackground(new java.awt.Color(232, 239, 239));

        jLabel21.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel21.setText("Payment");

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel22.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel22.setText("Card Number");

        cardNumberTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel23.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel23.setText("Card Holder Name");

        cardHolderTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel24.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel24.setText("End Date");

        monthSelection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        yearSelection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", " " }));

        jLabel25.setText("Month");

        jLabel26.setText("Year");

        jLabel27.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel27.setText("CVV");

        cvvTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        paybtn.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        paybtn.setText("Pay");
        paybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paybtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cardHolderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel22)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(monthSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel25))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel26)
                                .addComponent(yearSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(cardNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(paybtn, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addGap(138, 138, 138)
                                .addComponent(jLabel27)))
                        .addGap(18, 18, 18)
                        .addComponent(cvvTextField)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel23)
                .addGap(18, 18, 18)
                .addComponent(cardHolderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel22)
                .addGap(18, 18, 18)
                .addComponent(cardNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jLabel27)
                    .addComponent(cvvTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(monthSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(paybtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(200, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(393, 393, 393))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(billIDLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(billIDLabel)
                .addGap(34, 34, 34)
                .addComponent(jLabel21)
                .addGap(63, 63, 63)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(474, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab4", jPanel3);

        jPanel2.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1160, 990));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(MenuBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1160, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MenuBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1433, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1014, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editProfileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editProfileBtnActionPerformed
         DefaultTableModel vehicle = (DefaultTableModel)editVehicleTable.getModel();
         vehicle.setRowCount(0);
        jTabbedPane1.setSelectedIndex(1);
        residentNameTextField.setText("");
        residentICTextField.setText("");
        residentPhoneTextField.setText("");
        residentEmailTextField.setText("");
        
        loadResident2();
        
        
    }//GEN-LAST:event_editProfileBtnActionPerformed

    private void saveEditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveEditBtnActionPerformed
        conn = sqliteConn2.connect();
        
        String id = residentIDLabel.getText();
        String rname = residentNameTextField.getText();
        String ric = residentICTextField.getText();
        String rphone = residentPhoneTextField.getText();
        String remail = residentEmailTextField.getText();
        String sql1 = "UPDATE resident_account SET name =?,ic = ? ,contact=? ,email=? WHERE id= ? " ;
       if(conn !=null){
           if(rname.equals("")|| ric.equals("")|| rphone.equals("")|| remail.equals("")){
               JOptionPane.showMessageDialog(null,"Please");
           }else{
               try{
            pst =conn.prepareStatement(sql1);
            pst.setString(1,rname);
            pst.setString(2,ric);
            pst.setString(3,rphone);
            pst.setString(4,remail);
            pst.setString(5,id);
            pst.execute();
            JOptionPane.showMessageDialog(null,"Save Successfully");
            
            
           
        }
        catch(SQLException e){
                   JOptionPane.showMessageDialog(null,e);
            }finally {
    // Close resources (result set, statement, connection)
                if (rs != null) {
                    try {
                        rs.close();
                    } catch (SQLException e) {
                        // Handle exception
                    }
                }
                if (pst != null) {
                    try {
                        pst.close();
                    } catch (SQLException e) {
                        // Handle exception
                    }
                }
                if (conn != null) {
                    try {
                        conn.close();
                    } catch (SQLException e) {
                        // Handle exception
                    }
                }
            }
           }
        
       }

    }//GEN-LAST:event_saveEditBtnActionPerformed

    private void profilePanelbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profilePanelbtnActionPerformed
        jTabbedPane1.setSelectedIndex(0);
        DefaultTableModel residentCar = (DefaultTableModel)residentVehicleTabel.getModel();
        residentCar.setRowCount(0);
        residentNameLabel.setText("");
        residentICLabel.setText("");
        residentPhoneLabel.setText("");
        residentEmailLabel.setText("");
        loadResident();
    }//GEN-LAST:event_profilePanelbtnActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        addResidentVehicle addVehicle = new addResidentVehicle();
        String id = residentIDLabel.getText();
        addVehicle.idLabel.setText(id);
        addVehicle.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void deleteVehiclebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteVehiclebtnActionPerformed
        DefaultTableModel vehicleTable = (DefaultTableModel) editVehicleTable.getModel();
        conn = sqliteConn2.connect();
        int row = editVehicleTable.getSelectedRow();
        if(editVehicleTable.getSelectedRowCount() ==1){
            
            String id = editVehicleTable.getModel().getValueAt(row, 0).toString();
            
            String sql = "DELETE  FROM resident_vehicle WHERE id=?";
            
           
            vehicleTable.removeRow(editVehicleTable.getSelectedRow());
            
           
            try{
                pst = conn.prepareStatement(sql);
                pst.setString(1,id);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null,"Vechile unregistered successfully");
   
                
                
            }catch(SQLException e){
                   JOptionPane.showMessageDialog(null,e);
            }finally {
    // Close resources (result set, statement, connection)
            if (rs != null) {
                try {
                    rs.close();
                } catch (SQLException e) {
                    // Handle exception
                }
            }
            if (pst != null) {
                try {
                    pst.close();
                } catch (SQLException e) {
                    // Handle exception
                }
            }
            if (conn != null) {
                try {
                    conn.close();
                } catch (SQLException e) {
                    // Handle exception
                }
            }
        }

        
            
               
        }else{
                if(editVehicleTable.getRowCount()==0){
                    JOptionPane.showMessageDialog(this, "This table is empty");
                }else{
                    JOptionPane.showMessageDialog(this, "Please select one row of table to delete");
                }
     }
    }//GEN-LAST:event_deleteVehiclebtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jTabbedPane1.setSelectedIndex(2);
        DefaultTableModel pending = (DefaultTableModel)pendingTable.getModel();
        pending.setRowCount(0);
        DefaultTableModel history = (DefaultTableModel)historyTable.getModel();
        history.setRowCount(0);
        loadPendingPayment();
        loadHistoryPayment();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void paybyCreditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paybyCreditBtnActionPerformed
        DefaultTableModel pending = (DefaultTableModel) pendingTable.getModel();
        conn = sqliteConn2.connect();
        int row = pendingTable.getSelectedRow();
        if(pendingTable.getSelectedRowCount() ==1){
            
            String id = pendingTable.getModel().getValueAt(row, 0).toString();
            billIDLabel.setText(id);
            
            jTabbedPane1.setSelectedIndex(3);
            
           
            
            
               
        }else{
                if(editVehicleTable.getRowCount()==0){
                    JOptionPane.showMessageDialog(this, "This table is empty");
                }else{
                    JOptionPane.showMessageDialog(this, "Please select one row of table to delete");
                }
     }
    }//GEN-LAST:event_paybyCreditBtnActionPerformed

    private void paybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paybtnActionPerformed
            conn = sqliteConn2.connect();
            String cardName = cardHolderTextField.getText().toUpperCase();
            String cardNum = cardNumberTextField.getText().toUpperCase();
            String date = getCurrentDate();
            String cvv =cvvTextField.getText();
            String sql = "UPDATE bill_record SET payment_date=? ,payment_status='true' ,payment_method ='credit card' WHERE id =?";
            
            if(cardName.equals("") || cardNum.equals("") || cvv.equals("")){
                JOptionPane.showMessageDialog(null,"Please fill up all the fields");
            }else if(cardNum.length()<16 || cardNum.length()>16){
                JOptionPane.showMessageDialog(null,"Card number length is incorrect");
            }else if(cvv.length()!=3){
                JOptionPane.showMessageDialog(null,"CVV length is incorrect");
            }else if(!isNumeric(cvv)){
                JOptionPane.showMessageDialog(null,"Invalid CVV");
            }
            else{
               try{
                pst = conn.prepareStatement(sql);
                pst.setString(1, date);
                
                pst.setString(2, billIDLabel.getText());
                pst.execute();
                JOptionPane.showMessageDialog(null,"Payment Successfully");
                jTabbedPane1.setSelectedIndex(2);
                DefaultTableModel pending = (DefaultTableModel)pendingTable.getModel();
                pending.setRowCount(0);
                DefaultTableModel history = (DefaultTableModel)historyTable.getModel();
                history.setRowCount(0);
                loadPendingPayment();
                loadHistoryPayment();
                
                }catch(SQLException e){
                   JOptionPane.showMessageDialog(null,e);
                    }finally {
                    // Close resources (result set, statement, connection)
                    if (rs != null) {
                        try {
                            rs.close();
                        } catch (SQLException e) {
                            // Handle exception
                        }
                    }
                    if (pst != null) {
                        try {
                            pst.close();
                        } catch (SQLException e) {
                            // Handle exception
                        }
                    }
                    if (conn != null) {
                        try {
                            conn.close();
                        } catch (SQLException e) {
                            // Handle exception
                        }
                    }
                }
            }

    }//GEN-LAST:event_paybtnActionPerformed
    public void loadResident(){
        DefaultTableModel residentCar = (DefaultTableModel)residentVehicleTabel.getModel();
        
        
        conn = sqliteConn2.connect();
        
        String id = residentIDLabel.getText();
        String sql = "SELECT r.name ,rv.brand,rv.model,rv.plate_number,rv.color,r.ic,r.contact,r.email FROM resident_account r,resident_vehicle rv  WHERE r.id = rv.resident_id AND rv.resident_id = ?";
        
        try{
            pst = conn.prepareStatement(sql);
            pst.setString(1,id);
            rs = pst.executeQuery();
            while(rs.next()){
                
                String model = rs.getString("model");
                String brand = rs.getString("brand");
                String color = rs.getString("color");
                String plate_number = rs.getString("plate_number");
                String tbData[] ={brand,model,plate_number,color};
                
                residentCar.addRow(tbData);
                String name = rs.getString("name");
                String ic = rs.getString("ic");
                String contact = rs.getString("contact");
                String email = rs.getString("email");
                residentNameLabel.setText(name);
                residentICLabel.setText(ic);
                residentPhoneLabel.setText(contact);
                residentEmailLabel.setText(email);
                
            }
            if(rs.next()){
                
            }
        }catch(SQLException e){
                   JOptionPane.showMessageDialog(null,e);
            }finally {
    // Close resources (result set, statement, connection)
    if (rs != null) {
        try {
            rs.close();
        } catch (SQLException e) {
            // Handle exception
        }
    }
    if (pst != null) {
        try {
            pst.close();
        } catch (SQLException e) {
            // Handle exception
        }
    }
    if (conn != null) {
        try {
            conn.close();
        } catch (SQLException e) {
            // Handle exception
        }
    }
}
    }
    
    public void loadResident2(){
        DefaultTableModel vehicle = (DefaultTableModel)editVehicleTable.getModel();
        
        
        conn = sqliteConn2.connect();
        
        String id = residentIDLabel.getText();
        String sql = "SELECT rv.id, r.name ,rv.brand,rv.model,rv.plate_number,rv.color,r.name,r.ic,r.contact,r.email FROM resident_account r,resident_vehicle rv  WHERE r.id = rv.resident_id AND rv.resident_id = ?";
        
        try{
            pst = conn.prepareStatement(sql);
            pst.setString(1,id);
            rs = pst.executeQuery();
            while(rs.next()){
                String tblid = rs.getString("id");
                String model = rs.getString("model");
                String brand = rs.getString("brand");
                String color = rs.getString("color");
                String plate_number = rs.getString("plate_number");
                String tbData[] ={tblid,brand,model,plate_number,color};
                
                vehicle.addRow(tbData);
                String name = rs.getString("name");
                String ic = rs.getString("ic");
                String contact = rs.getString("contact");
                String email = rs.getString("email");
                 residentNameTextField.setText(name);
                residentICTextField.setText(ic);
                residentPhoneTextField.setText(contact);
                residentEmailTextField.setText(email);
               
            }
            
        }catch(SQLException e){
                   JOptionPane.showMessageDialog(null,e);
            }finally {
    // Close resources (result set, statement, connection)
    if (rs != null) {
        try {
            rs.close();
        } catch (SQLException e) {
            // Handle exception
        }
    }
    if (pst != null) {
        try {
            pst.close();
        } catch (SQLException e) {
            // Handle exception
        }
    }
    if (conn != null) {
        try {
            conn.close();
        } catch (SQLException e) {
            // Handle exception
        }
    }
}
    }
    
public void loadPendingPayment(){
        DefaultTableModel pending = (DefaultTableModel)pendingTable.getModel();
       
        conn = sqliteConn2.connect();
        String unit = residentUnitLabel.getText();
        String sql = "SELECT id,bill_type,bill_amount FROM bill_record WHERE floor_unit = ? AND payment_status ='false' ";
        
        try{
            pst = conn.prepareStatement(sql);
            pst.setString(1,unit);
            rs = pst.executeQuery();
            while(rs.next()){
                String tblid = rs.getString("id");
                String type = rs.getString("bill_type");
                String amount = rs.getString("bill_amount");
                
                String tbData[] ={tblid,type,amount};
                
                pending.addRow(tbData);
               
               
            }
            
        }catch(SQLException e){
                   JOptionPane.showMessageDialog(null,e);
            }finally {
            // Close resources (result set, statement, connection)
            if (rs != null) {
                try {
                    rs.close();
                } catch (SQLException e) {
                    // Handle exception
                }
            }
            if (pst != null) {
                try {
                    pst.close();
                } catch (SQLException e) {
                    // Handle exception
                }
            }
            if (conn != null) {
                try {
                    conn.close();
                } catch (SQLException e) {
                    // Handle exception
                }
            }
        }
    }

public void loadHistoryPayment(){
        DefaultTableModel history = (DefaultTableModel)historyTable.getModel();
       
        conn = sqliteConn2.connect();
        String unit = residentUnitLabel.getText();
        String sql = "SELECT id,bill_type,payment_date FROM bill_record WHERE floor_unit = ? AND payment_status ='true' ";
        
        try{
            pst = conn.prepareStatement(sql);
            pst.setString(1,unit);
            rs = pst.executeQuery();
            while(rs.next()){
                String tblid = rs.getString("id");
                String type = rs.getString("bill_type");
                String date = rs.getString("payment_date");
                
                String tbData[] ={tblid,type,date};
                
                history.addRow(tbData);
               
               
            }
            
        }catch(SQLException e){
                   JOptionPane.showMessageDialog(null,e);
            }finally {
            // Close resources (result set, statement, connection)
            if (rs != null) {
                try {
                    rs.close();
                } catch (SQLException e) {
                    // Handle exception
                }
            }
            if (pst != null) {
                try {
                    pst.close();
                } catch (SQLException e) {
                    // Handle exception
                }
            }
            if (conn != null) {
                try {
                    conn.close();
                } catch (SQLException e) {
                    // Handle exception
                }
            }
        }
    }
private String getCurrentDate() {
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    Date currentDate = new Date();
    return dateFormat.format(currentDate);
    }
public static boolean isNumeric(String input) {
    try {
        double d = Double.parseDouble(input);
        // Parsing succeeded, so it is numeric
        return true;
    } catch (NumberFormatException e) {
        // Parsing failed, so it is not numeric
        return false;
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResidentMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResidentMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResidentMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResidentMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResidentMainPage().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame LoginFrame;
    private javax.swing.JPanel MenuBarPanel;
    private javax.swing.JLabel billIDLabel;
    private javax.swing.JPanel billPanel;
    private javax.swing.JTextField cardHolderTextField;
    private javax.swing.JTextField cardNumberTextField;
    private javax.swing.JTextField cvvTextField;
    private javax.swing.JButton deleteVehiclebtn;
    private javax.swing.JButton editProfileBtn;
    private javax.swing.JPanel editResidentProfilePanel;
    private javax.swing.JTable editVehicleTable;
    private javax.swing.JTable historyTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JComboBox<String> monthSelection;
    private javax.swing.JButton paybtn;
    private javax.swing.JButton paybyCreditBtn;
    private javax.swing.JTable pendingTable;
    private javax.swing.JButton profilePanelbtn;
    private javax.swing.JLabel residentEmailLabel;
    private javax.swing.JTextField residentEmailTextField;
    private javax.swing.JLabel residentICLabel;
    private javax.swing.JTextField residentICTextField;
    public javax.swing.JLabel residentIDLabel;
    private javax.swing.JLabel residentNameLabel;
    private javax.swing.JTextField residentNameTextField;
    private javax.swing.JLabel residentPhoneLabel;
    private javax.swing.JTextField residentPhoneTextField;
    private javax.swing.JPanel residentProfilePanel;
    public javax.swing.JLabel residentUnitLabel;
    private javax.swing.JTable residentVehicleTabel;
    private javax.swing.JButton saveEditBtn;
    private javax.swing.JComboBox<String> yearSelection;
    // End of variables declaration//GEN-END:variables
}
